// Sample data for homepage components (for development/testing)
// This will be replaced with Strapi data once the CMS is populated

export const sampleHomepageData = {
  heroSection: {
    badge: "Professional Hosting Solutions",
    heading: "All in one Web hosting\nfor your business",
    description: "Keep your website running smoothly with reliable hosting solutions. Manage domains, hosting, and applications quickly, easily & efficiently.",
    primaryCta: {
      text: "Get Started",
      variant: "default" as const,
      size: "lg" as const,
    },
    secondaryCta: {
      text: "View Pricing",
      variant: "ghost" as const,
      size: "lg" as const,
      href: "/hosting/shared",
    },
    heroImage: {
      url: "/images/Hero-Right-Side-Image.jpg",
      alt: "Momtaz Host Dashboard",
      width: 600,
      height: 500,
    },
    socialProof: {
      statNumber: "12k+",
      statLabel: "Trusted by businesses worldwide",
      avatars: [
        { initials: "A", backgroundColor: "primary" as const },
        { initials: "M", backgroundColor: "secondary" as const },
        { initials: "S", backgroundColor: "accent" as const },
      ],
    },
  },
  companyLogos: {
    logos: [
      { name: "slack" },
      { name: "zoom" },
      { name: "airbnb" },
      { name: "spotify" },
      { name: "envato" },
    ],
  },
  domainSearch: {
    heading: "Find Your Perfect Domain",
    description: "Search for available domains including .af domains for Afghanistan",
    placeholder: "Enter your domain name",
    tlds: [
      { value: ".com", label: ".com" },
      { value: ".org", label: ".org" },
      { value: ".net", label: ".net" },
      { value: ".af", label: ".af" },
      { value: ".af.com", label: ".af.com" },
      { value: ".af.org", label: ".af.org" },
      { value: ".af.net", label: ".af.net" },
    ],
    features: [
      { text: "Free SSL Certificate" },
      { text: "Domain Privacy Protection" },
      { text: "24/7 Support" },
    ],
  },
  servicesSection: {
    heading: "One Partner. All Your Digital Needs.",
    description: "Explore our complete range of services tailored\nfor individuals, startups, and enterprises.",
    services: [
      {
        title: "Advanced Web Hosting Solutions",
        description: "Experience lightning-fast performance with our enterprise-grade hosting infrastructure. From shared hosting for small websites to dedicated servers for high-traffic applications, we provide scalable solutions with 99.9% uptime guarantee and 24/7 expert support.",
        icon: "Server",
        imageUrl: "/images/Hero-Right-Side-Image.jpg",
        imageAlt: "Hosting Dashboard Interface",
      },
      {
        title: "Professional Domain Management",
        description: "Secure your perfect domain name with our comprehensive domain registration services. We support all major TLDs including .af domains for Afghanistan, with free SSL certificates, domain privacy protection, and seamless DNS management.",
        icon: "Globe",
        imageUrl: "/images/Hero-Right-Side-Image.jpg",
        imageAlt: "Domain Management Interface",
      },
      {
        title: "Google Workspace Integration",
        description: "As an official Google Partner, we help you set up and manage professional business email, cloud storage, and team collaboration tools. Get Gmail, Drive, Docs, Meet, and more under your custom domain with seamless integration.",
        icon: "Mail",
        imageUrl: "/images/Hero-Right-Side-Image.jpg",
        imageAlt: "Google Workspace Dashboard",
      },
      {
        title: "Custom Web Development",
        description: "Transform your ideas into stunning, responsive websites that deliver exceptional user experiences. Our expert developers create modern, mobile-first websites using the latest technologies and best practices for optimal performance.",
        icon: "Code",
        imageUrl: "/images/Hero-Right-Side-Image.jpg",
        imageAlt: "Web Development Process",
      },
      {
        title: "SEO & Digital Branding",
        description: "Boost your online visibility and establish a strong digital presence with our comprehensive SEO services and branding solutions. We help you rank higher in search results, attract more traffic, and grow your business with data-driven strategies.",
        icon: "Search",
        imageUrl: "/images/Hero-Right-Side-Image.jpg",
        imageAlt: "SEO Analytics Dashboard",
      },
      {
        title: "Database & Application Development",
        description: "Build powerful, scalable applications with our custom database and web application development services. From simple CRUD applications to complex enterprise systems, we create solutions tailored to your specific business requirements.",
        icon: "Database",
        imageUrl: "/images/Hero-Right-Side-Image.jpg",
        imageAlt: "Database Development Interface",
      },
      {
        title: "Mobile App Development",
        description: "Reach your customers on every device with our native and cross-platform mobile app development services. We create iOS and Android apps with seamless performance, intuitive user interfaces, and robust backend integration.",
        icon: "Smartphone",
        imageUrl: "/images/Hero-Right-Side-Image.jpg",
        imageAlt: "Mobile App Development",
      },
      {
        title: "Digital Marketing & Growth",
        description: "Accelerate your business growth with our comprehensive digital marketing strategies. From social media management to content marketing, PPC campaigns, and conversion optimization, we help you reach and engage your target audience effectively.",
        icon: "Heart",
        imageUrl: "/images/Hero-Right-Side-Image.jpg",
        imageAlt: "Digital Marketing Analytics",
      },
    ],
  },
  pricingSection: {
    heading: "Choose Your Perfect Hosting Plan",
    description: "From shared hosting to powerful VPS solutions, we have the perfect plan for your needs.",
    plans: [
      {
        name: "Shared Hosting",
        description: "Perfect for small websites",
        price: "$2.99",
        period: "/month",
        features: [
          { text: "10GB SSD Storage" },
          { text: "Unlimited Bandwidth" },
          { text: "Free SSL Certificate" },
          { text: "24/7 Support" },
        ],
        isPopular: false,
        ctaButton: {
          text: "Get Started",
          variant: "default" as const,
          size: "default" as const,
          href: "/hosting/shared",
        },
      },
      {
        name: "VPS Hosting",
        description: "Scalable virtual servers",
        price: "$19.99",
        period: "/month",
        features: [
          { text: "50GB SSD Storage" },
          { text: "2GB RAM" },
          { text: "Root Access" },
          { text: "Free Migration" },
        ],
        isPopular: true,
        badgeText: "Most Popular",
        ctaButton: {
          text: "Get Started",
          variant: "default" as const,
          size: "default" as const,
          href: "/hosting/vps",
        },
      },
      {
        name: "Cloud Hosting",
        description: "High-performance cloud",
        price: "$39.99",
        period: "/month",
        features: [
          { text: "100GB SSD Storage" },
          { text: "4GB RAM" },
          { text: "Auto Scaling" },
          { text: "CDN Included" },
        ],
        isPopular: false,
        ctaButton: {
          text: "Get Started",
          variant: "default" as const,
          size: "default" as const,
          href: "/hosting/cloud",
        },
      },
      {
        name: "Windows Hosting",
        description: "ASP.NET & Windows apps",
        price: "$29.99",
        period: "/month",
        features: [
          { text: "75GB SSD Storage" },
          { text: "3GB RAM" },
          { text: "IIS 10 Support" },
          { text: "SQL Server" },
        ],
        isPopular: false,
        ctaButton: {
          text: "Get Started",
          variant: "default" as const,
          size: "default" as const,
          href: "/hosting/windows",
        },
      },
    ],
    ctaText: "Need help choosing the right plan?",
    ctaButton: {
      text: "Contact Our Experts",
      variant: "outline" as const,
      size: "lg" as const,
      href: "/contact",
    },
  },
  whyChooseUs: {
    heading: "Why Choose Momtaz Host?",
    description: "We're committed to providing the best hosting experience with unmatched reliability, security, and support.",
    features: [
      {
        title: "99.9% Uptime Guarantee",
        description: "Your website stays online with our industry-leading uptime guarantee. We monitor our servers 24/7 to ensure maximum availability.",
        icon: "CheckCircle",
        iconColor: "green-600",
      },
      {
        title: "24/7 Expert Support",
        description: "Our experienced support team is available around the clock to help you with any hosting-related questions or issues.",
        icon: "Support",
        iconColor: "blue-600",
      },
      {
        title: "Free SSL Certificates",
        description: "Secure your website with free SSL certificates. All our hosting plans include automatic SSL installation and renewal.",
        icon: "Shield",
        iconColor: "purple-600",
      },
      {
        title: "Lightning Fast Speed",
        description: "Experience blazing-fast website loading times with our SSD storage, CDN integration, and optimized server configurations.",
        icon: "Zap",
        iconColor: "orange-600",
      },
      {
        title: "Free Website Migration",
        description: "Moving from another host? Our experts will migrate your website for free with zero downtime and no data loss.",
        icon: "Download",
        iconColor: "teal-600",
      },
      {
        title: "30-Day Money Back",
        description: "Not satisfied? Get a full refund within 30 days. We're confident you'll love our hosting services.",
        icon: "ShieldCheck",
        iconColor: "red-600",
      },
    ],
    stats: [
      { number: "12,000+", label: "Happy Customers" },
      { number: "99.9%", label: "Uptime Guarantee" },
      { number: "24/7", label: "Expert Support" },
      { number: "5+", label: "Years Experience" },
    ],
  },
  googleWorkspace: {
    heading: "Professional Email &\nCollaboration - Powered by\nGoogle",
    description: "As an official Google Workspace Partner, we help you set up and manage professional business email, cloud storage, and team collaboration tools like Gmail, Drive, Docs, Meet, and more — all under your custom domain.",
    image: {
      url: "/images/google-workspace.jpg",
      alt: "Google Workspace Dashboard",
      width: 600,
      height: 500,
    },
    features: [
      { text: "Business-grade Gmail with your domain name" },
      { text: "Secure cloud storage and file sharing" },
      { text: "Calendar, Meet, and Docs for seamless teamwork" },
    ],
    primaryCta: {
      text: "Get Started",
      variant: "default" as const,
      size: "lg" as const,
    },
    secondaryCta: {
      text: "View Pricing",
      variant: "ghost" as const,
      size: "lg" as const,
      href: "/hosting/shared",
    },
  },
  testimonials: {
    heading: "What Our Customers Say",
    description: "Don't just take our word for it. Here's what our satisfied customers have to say about their experience with Momtaz Host.",
    testimonials: [
      {
        quote: "Momtaz Host has been incredible for our business. The uptime is excellent, and their support team is always there when we need them. Highly recommended!",
        author: "Ahmad Zahir",
        position: "CEO, Tech Solutions",
        rating: 5,
        avatar: { initials: "A", backgroundColor: "primary" as const },
      },
      {
        quote: "The migration process was seamless, and our website has never been faster. The VPS hosting plan is perfect for our growing e-commerce business.",
        author: "Sara Mohammadi",
        position: "Founder, Online Store",
        rating: 5,
        avatar: { initials: "S", backgroundColor: "secondary" as const },
      },
      {
        quote: "Outstanding service! The 24/7 support is amazing, and they helped us set up our domain and hosting in no time. Great value for money.",
        author: "Mohammad Karimi",
        position: "Web Developer",
        rating: 5,
        avatar: { initials: "M", backgroundColor: "accent" as const },
      },
      {
        quote: "The cloud hosting solution is perfect for our startup. Auto-scaling and CDN integration have improved our site performance significantly.",
        author: "Fatima Ahmadi",
        position: "CTO, StartupCo",
        rating: 5,
        avatar: { initials: "F", backgroundColor: "primary" as const },
      },
      {
        quote: "Excellent Windows hosting for our ASP.NET applications. The SQL Server integration and IIS support are top-notch. Highly professional service.",
        author: "Hassan Rezaei",
        position: "Software Engineer",
        rating: 5,
        avatar: { initials: "H", backgroundColor: "secondary" as const },
      },
      {
        quote: "The free migration service was incredible. They moved our entire website without any downtime. The team is knowledgeable and very responsive.",
        author: "Nargis Hashemi",
        position: "Marketing Director",
        rating: 5,
        avatar: { initials: "N", backgroundColor: "accent" as const },
      },
    ],
    overallRating: {
      rating: 4.9,
      maxRating: 5,
      reviewCount: "1,247 reviews",
      description: "from satisfied customers",
      ctaText: "Read More Reviews",
    },
  },
  enhancedCta: {
    heading: "Ready to Get Started?",
    description: "Join thousands of satisfied customers who trust Momtaz Host for their hosting needs. Get started today and experience the difference.",
    primaryCta: {
      text: "Get Started Now",
      variant: "default" as const,
      size: "lg" as const,
    },
    secondaryCta: {
      text: "Contact Sales",
      variant: "ghost" as const,
      size: "lg" as const,
      href: "/hosting/shared",
    },
    trustIndicators: [
      {
        title: "Quick Setup",
        description: "Get your website online in minutes with our easy setup process",
        icon: "Settings2",
      },
      {
        title: "Secure & Reliable",
        description: "99.9% uptime guarantee with enterprise-grade security",
        icon: "Fingerprint",
      },
      {
        title: "24/7 Support",
        description: "Expert support team available around the clock to help you",
        icon: "Headset",
      },
    ],
    finalCta: {
      heading: "Still Have Questions?",
      description: "Our team of experts is here to help you choose the perfect hosting solution for your needs.",
      primaryCta: {
        text: "Get Free Consultation",
        variant: "default" as const,
        size: "lg" as const,
        href: "/contact",
      },
      secondaryCta: {
        text: "View FAQ",
        variant: "outline" as const,
        size: "lg" as const,
        href: "/faq",
      },
    },
  },
};

