#!/bin/bash

echo "==================================="
echo "Layout Structure Verification"
echo "==================================="
echo ""

echo "✅ Root Layout (base structure only):"
echo "   File: src/app/layout.tsx"
grep -q "Header" src/app/layout.tsx && echo "   ❌ ERROR: Contains Header" || echo "   ✓ No Header"
grep -q "Footer" src/app/layout.tsx && echo "   ❌ ERROR: Contains Footer" || echo "   ✓ No Footer"
echo ""

echo "✅ Main Layout (with Header/Footer):"
echo "   File: src/app/(main)/layout.tsx"
[ -f "src/app/(main)/layout.tsx" ] && echo "   ✓ File exists" || echo "   ❌ ERROR: File missing"
grep -q "Header" src/app/(main)/layout.tsx && echo "   ✓ Has Header" || echo "   ❌ ERROR: Missing Header"
grep -q "Footer" src/app/(main)/layout.tsx && echo "   ✓ Has Footer" || echo "   ❌ ERROR: Missing Footer"
echo ""

echo "✅ Auth Layout (no Header/Footer):"
echo "   File: src/app/(auth)/layout.tsx"
[ -f "src/app/(auth)/layout.tsx" ] && echo "   ✓ File exists" || echo "   ❌ ERROR: File missing"
grep -q "Header" src/app/(auth)/layout.tsx && echo "   ❌ ERROR: Contains Header" || echo "   ✓ No Header"
grep -q "Footer" src/app/(auth)/layout.tsx && echo "   ❌ ERROR: Contains Footer" || echo "   ✓ No Footer"
echo ""

echo "✅ Dashboard Layout (no Header/Footer):"
echo "   File: src/app/(dashboard)/layout.tsx"
[ -f "src/app/(dashboard)/layout.tsx" ] && echo "   ✓ File exists" || echo "   ❌ ERROR: File missing"
grep -q "Header" src/app/(dashboard)/layout.tsx && echo "   ❌ ERROR: Contains Header" || echo "   ✓ No Header"
grep -q "Footer" src/app/(dashboard)/layout.tsx && echo "   ❌ ERROR: Contains Footer" || echo "   ✓ No Footer"
echo ""

echo "✅ Page Locations:"
echo "   Main pages:"
[ -f "src/app/(main)/page.tsx" ] && echo "   ✓ Homepage in (main)" || echo "   ❌ Homepage missing"
[ -f "src/app/(main)/about/page.tsx" ] && echo "   ✓ About in (main)" || echo "   ❌ About missing"
echo ""
echo "   Auth pages:"
[ -f "src/app/(auth)/login/page.tsx" ] && echo "   ✓ Login in (auth)" || echo "   ❌ Login missing"
[ -f "src/app/(auth)/signup/page.tsx" ] && echo "   ✓ Signup in (auth)" || echo "   ❌ Signup missing"
echo ""
echo "   Dashboard pages:"
[ -f "src/app/(dashboard)/dashboard/page.tsx" ] && echo "   ✓ Dashboard in (dashboard)" || echo "   ❌ Dashboard missing"
echo ""

echo "==================================="
echo "Verification Complete!"
echo "==================================="
